# Site settings
title: A portfolio website for Sarah Bump
description: A portfolio website for Sarah Bump
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sarah Bump
user_description: Greetings! I am full stack web developer, technical product manager, and writer with a focus on civic technology. I like to combine different mediums to create dynamic work that has a positive impact on my community. With JavaScript, data visualizations, and editorials, I am hoping to fight for social justice and environmental sustainability.
user_title: Software Developer. Civic Technologist. Media Junkie.
email: sbump90@gmail.com
twitter_username: sarahbumpsnc12
github_username:  sarahBump

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
